//! hipfire-runtime: GGUF model loading and LLaMA inference on RDNA GPUs.

pub mod arch;
pub mod gguf;
pub mod hfq;
pub mod llama;
pub mod loop_guard;
pub mod sampler;
#[cfg(feature = "deltanet")]
pub mod qwen35;
#[cfg(feature = "deltanet")]
pub mod qwen35_vl;
#[cfg(feature = "deltanet")]
pub mod speculative;
#[cfg(feature = "deltanet")]
pub mod dflash;
#[cfg(feature = "deltanet")]
pub mod ddtree;
#[cfg(feature = "deltanet")]
pub mod triattn;
#[cfg(feature = "deltanet")]
pub mod cask;
#[cfg(feature = "deltanet")]
pub mod cpu_router;
#[cfg(feature = "deltanet")]
pub mod weight_pager;
pub mod image;
pub mod tokenizer;
pub mod pflash;
pub mod eos_filter;
pub mod prompt_frame;
